### PR TITLE
fix: library model has to reset session id on profile change

### LINKED ISSUE #250: Switch back to  the specified profile, error happened and it failed to load data under Libraries section
**Describe the bug**
Install the SAS extension package generated base on the main branch. Sign in successfully with the specified profile. Switch to a new valid profile and Cancel the sign in (User did not consent to login). Switch back to the previous one, it will get 'Request failed with status code 401' error and it failed to load data under Libaraies section. Try to refresh the Libarary, the error happened again. 

**Steps to reproduce**

1.Sign in to show contents pane with a valid profile
2.Switch to a new valid profile and Cancel the sign in (it will show the message 'User did not consent to login' as expected )
3.Switch back to the previous one

**Expected behavior**
No error to switch back 

**Screenshots**
image

**Environment (please complete the following information):**
Client OS: [e.g. Windows 11]
Extension version: [e.g. v0.1.1]

### PR DESCRIPTION
**Pull request by scnwwu**
**Summary**
Fix #250, #252 and #265
Library model has to reset session id on profile change
Also cleaned up some unused fields in LibraryModel

**Testing**
Test case in #250

### CODE REVIEW

File: client/src/components/LibraryNavigator/LibraryDataProvider.ts [hunk 1]
```diff
@@ -17,24 +16,16 @@ import LibraryModel from "./LibraryModel";
...
+  private _onDidChangeTreeData = new EventEmitter<LibraryItem | undefined>();
 
   get onDidChangeTreeData(): Event<LibraryItem> {
     return this._onDidChangeTreeData.event;
   }
 
-  constructor(model: LibraryModel, extensionUri: Uri) {
-    this._onDidChangeTreeData = new EventEmitter<LibraryItem | undefined>();
-    this.model = model;
-    this.dragMimeTypes = ["application/vnd.code.tree.libraryDragAndDrop"];
```
Comment (scottdover) [inline client/src/components/LibraryNavigator/LibraryDataProvider.ts:35]: Is there going to be an issue with removing `dragMimeTypes` here? Did you test dragging a table into a sas program?

Comment (scnwwu) [reply client/src/components/LibraryNavigator/LibraryDataProvider.ts:35]: I searched the whole project and this property is not used anywhere. It's indeed misleading. So I thought it's a good idea to clean this up.
I tried dragging a table into sas program and it does NOT work even on main branch. It's not impacted by this line.
I've gone ahead made an additional fix for the dragging issue. Please review. Thanks.

**Review by scottdover — APPROVED** [review]

**Review by Zhirong2022 — APPROVED** [review]
