### PR TITLE
fix: output log in running tasks

### LINKED ISSUE #1058: Since v1.10.0, Terminal -> Run Task -> 'sas: Run sas file' does not produce any log in the OUTPUT pane
**Describe the bug**
Since v1.10.0, submitting SAS code using the menu Terminal -> Run Task -> 'sas: Run sas file' does not produce any visible log in the OUTPUT pane anymore (observed using local profile).  This was working in the previous version.

Only when submitting with F3 or F8 do I see the log in the output pane.

**Expected behavior**
Log should be visible even when submitting with "Run Task"

**Screenshots**
NA

**Environment (please complete the following information):**
Client OS:  Windows 10
Extension version: v1.10.0
SAS version: SAS 9.4 TS1M8

### PR DESCRIPTION
**Pull request by scnjdl**
**Summary**
Log will be shown in output panel
Fix #1058 

**Testing**
Run task
see log is shown in output panel

### CODE REVIEW

File: client/src/commands/run.ts [hunk 1]
```diff
@@ -204,14 +215,39 @@ export async function runTask(
...
   messageEmitter.fire(`${l10n.t("SAS code running...")}\r\n`);
-  return cancelled ? undefined : session.run(code);
+  return cancelled
+    ? undefined
+    : session.run(codeDoc.getWrappedCode()).then((results) => {
+        showRunResult(results, messageEmitter, taskLabel);
+      });
+}
+
+function showRunResult(
```
Comment (scnwwu) [inline client/src/commands/run.ts:236]: I would suggest to keep `showRunResult` in `SasTasks.ts` as before. It's task-specific.

**Review by scnwwu — APPROVED** [review]

**Comment by Zhirong2022** [comment]
Log contents are shown on output panel as expected through 'Run task'.

**Review by Zhirong2022 — APPROVED** [review]
